### ISSUE TITLE
1.2: PHP warning emitted when channel binding fails

### ISSUE THREAD

**Issue by tvdijen** [php/pecl-authentication-krb5#9]
When I specify the wrong hash in the binding-object, ::doAuthentication will emit a PHP warning:

```
    $binding = new GSSAPIChannelBinding();
    $binding->setApplicationData(
        'tls-server-end-point:' . pack('H*', "A1B2C3D4E5F6"),  // some hash from the wrong certificate
    );
    $auth = new KRB5NegotiateAuth($keytab, $spn, $binding);
    $auth->doAuthentication();  // Warning is being emitted

```

```
Jun 19 11:12:20 IDP[2302691]: PHP Warning:  KRB5NegotiateAuth::doAuthentication(): Success (100002)
```

With the correct hash, the warning is not emitted

**Comment by mbechler** [comment]
What would you expect to happen? If a wrong hash is set and the client supplies the correct binding data the accept_sec_context call should fail. The extensions error handling generally, if a GSSAPI calls returns an error status, logs the error details as warnings. I do however get more error information:

```
<b>Warning</b>:  KRB5NegotiateAuth::doAuthentication(): Incorrect channel bindings were supplied (262144,100005) in <b>/var/www/localhost/htdocs/spnego.php</b> on line <b>18</b><br />
<br />
<b>Warning</b>:  KRB5NegotiateAuth::doAuthentication(): GSSAPI mechanism error #100005 in <b>/var/www/localhost/htdocs/spnego.php</b> on line <b>18</b><br />
<br />
<b>Warning</b>:  KRB5NegotiateAuth::doAuthentication(): Success (100005) in <b>/var/www/localhost/htdocs/spnego.php</b> on line <b>18</b><br />
```

**Comment by tvdijen** [comment]
I would expect it to throw an exception that I can catch, instead of emitting a warning and have PHP execution silently continue..

Also, I think the `success` in the warning message is misleading..

**Comment by mbechler** [comment]
Oh, yes it absolutely should, and did in my testing. Maybe something real strange was going on due to the memory error.

**Comment by tvdijen** [comment]
Ok, I'm actually mistaking.. The code _does_ throw a generic `\Exception`.
The difference with your test, I think, is that you're doing `basic` authentication and I'm using `negotiate`, so that might explain the difference in warnings.

**Comment by mbechler** [comment]
Mine was negotiate as well. But the different error might as well be an artefact of different kerberos libraries or versions.
